"""update of tables

Revision ID: 4a1495f8e3ee
Revises: 13fed0eebd84
Create Date: 2025-08-08 15:57:09.260085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a1495f8e3ee'
down_revision: Union[str, Sequence[str], None] = '13fed0eebd84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodation_bookings', sa.Column('property_token', sa.String(), nullable=True))
    op.add_column('accommodation_bookings', sa.Column('hotel_class', sa.Integer(), nullable=True))
    op.add_column('accommodation_bookings', sa.Column('accommodation_name', sa.String(), nullable=True))
    op.add_column('accommodation_bookings', sa.Column('accommodation_type', sa.String(), nullable=True))
    op.add_column('accommodation_bookings', sa.Column('accommodation_rating', sa.Float(), nullable=True))
    op.add_column('accommodation_bookings', sa.Column('accommodation_reviews', sa.Integer(), nullable=True))
    op.add_column('accommodation_bookings', sa.Column('accommodation_amenities', sa.JSON(), nullable=True))
    op.add_column('accommodation_bookings', sa.Column('accommodation_images', sa.JSON(), nullable=True))
    op.add_column('accommodation_bookings', sa.Column('accommodation_formatted_images', sa.JSON(), nullable=True))
    op.add_column('accommodation_bookings', sa.Column('accommodation_link', sa.String(), nullable=True))
    op.add_column('accommodation_bookings', sa.Column('accommodation_formatted_link', sa.String(), nullable=True))
    op.add_column('accommodation_bookings', sa.Column('accommodation_location', sa.JSON(), nullable=True))
    op.add_column('accommodation_bookings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('accommodation_bookings', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('accommodation_bookings', 'thread_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('accommodation_bookings', 'booking_reference',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('accommodation_bookings', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('accommodation_bookings', 'guest_names',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('accommodation_bookings', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('accommodation_bookings', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('accommodation_bookings', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_accommodation_bookings_booking_reference'), 'accommodation_bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_accommodation_bookings_thread_id'), 'accommodation_bookings', ['thread_id'], unique=False)
    op.create_index(op.f('ix_accommodation_bookings_user_id'), 'accommodation_bookings', ['user_id'], unique=False)
    op.drop_column('accommodation_bookings', 'booking_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodation_bookings', sa.Column('booking_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_accommodation_bookings_user_id'), table_name='accommodation_bookings')
    op.drop_index(op.f('ix_accommodation_bookings_thread_id'), table_name='accommodation_bookings')
    op.drop_index(op.f('ix_accommodation_bookings_booking_reference'), table_name='accommodation_bookings')
    op.alter_column('accommodation_bookings', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('accommodation_bookings', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('accommodation_bookings', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('accommodation_bookings', 'guest_names',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('accommodation_bookings', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('accommodation_bookings', 'booking_reference',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('accommodation_bookings', 'thread_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('accommodation_bookings', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('accommodation_bookings', 'updated_at')
    op.drop_column('accommodation_bookings', 'accommodation_location')
    op.drop_column('accommodation_bookings', 'accommodation_formatted_link')
    op.drop_column('accommodation_bookings', 'accommodation_link')
    op.drop_column('accommodation_bookings', 'accommodation_formatted_images')
    op.drop_column('accommodation_bookings', 'accommodation_images')
    op.drop_column('accommodation_bookings', 'accommodation_amenities')
    op.drop_column('accommodation_bookings', 'accommodation_reviews')
    op.drop_column('accommodation_bookings', 'accommodation_rating')
    op.drop_column('accommodation_bookings', 'accommodation_type')
    op.drop_column('accommodation_bookings', 'accommodation_name')
    op.drop_column('accommodation_bookings', 'hotel_class')
    op.drop_column('accommodation_bookings', 'property_token')
    # ### end Alembic commands ###
