"""Add flight_number to FlightLegDB

Revision ID: 78d1f98d2221
Revises: 1bfc91965647
Create Date: 2025-07-29 15:31:40.455658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78d1f98d2221'
down_revision: Union[str, Sequence[str], None] = '1bfc91965647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_bookings', sa.Column('total_price', sa.Float(), nullable=True))
    op.add_column('flight_bookings', sa.Column('price_breakdown', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('flight_bookings', 'price')
    op.add_column('flight_legs', sa.Column('flight_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_legs', 'flight_number')
    op.add_column('flight_bookings', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('flight_bookings', 'price_breakdown')
    op.drop_column('flight_bookings', 'total_price')
    # ### end Alembic commands ###
