"""Add airlines to FlightBooking and airline, flight_number to FlightSegmentDB

Revision ID: adf7ca8c4f77
Revises: ae88d58ee266
Create Date: 2025-08-02 14:50:35.188531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf7ca8c4f77'
down_revision: Union[str, Sequence[str], None] = 'ae88d58ee266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_bookings', sa.Column('airlines', sa.JSON(), nullable=True))
    op.drop_column('flight_bookings', 'airline')
    op.add_column('flight_segments', sa.Column('airline', sa.String(), nullable=True))
    op.add_column('flight_segments', sa.Column('flight_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_segments', 'flight_number')
    op.drop_column('flight_segments', 'airline')
    op.add_column('flight_bookings', sa.Column('airline', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('flight_bookings', 'airlines')
    # ### end Alembic commands ###
