"""Add flight_number to flight_legs

Revision ID: fab55d3ea86e
Revises: 78d1f98d2221
Create Date: 2025-07-29 15:46:50.438619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab55d3ea86e'
down_revision: Union[str, Sequence[str], None] = '78d1f98d2221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
